export interface GlossaryTerm {
  slug: string;
  term: string;
  definition: string;
  relatedMethodSlug?: string;
}

/**
 * Glossaire de la transformation digitale, dérivé du contenu réel du cours
 * (cf. src/lib/methode-content.ts) — aucune définition inventée : chaque
 * terme est déjà utilisé et expliqué dans les 17 chapitres publiés.
 */
export const GLOSSARY_TERMS: GlossaryTerm[] = [
  { slug: "as-is-to-be", term: "AS-IS / TO-BE", definition: "L'AS-IS décrit le fonctionnement réel actuel d'un processus (étapes, rôles, systèmes, données, exceptions). Le TO-BE en décrit la version cible simplifiée. On cartographie toujours l'AS-IS avant de concevoir le TO-BE, jamais l'inverse.", relatedMethodSlug: "processus-bpmn-lean-refonte" },
  { slug: "ai-act", term: "AI Act", definition: "Règlement européen encadrant l'intelligence artificielle, qui impose depuis le 2 août 2026 des obligations de transparence dans certaines interactions avec des systèmes IA et pour certains contenus générés. Les obligations précises dépendent du rôle et du cas d'usage.", relatedMethodSlug: "ia-rag-agents-mcp" },
  { slug: "agent-ia", term: "Agent IA", definition: "Boucle de décision qui sélectionne des actions ou des outils jusqu'à un résultat ou une condition d'arrêt. Un agent unique avec des outils explicites est plus simple à tester que plusieurs agents choisis pour l'effet de démonstration.", relatedMethodSlug: "ia-rag-agents-mcp" },
  { slug: "api", term: "API", definition: "Interface qui expose des opérations qu'un autre système peut demander (lire un client, créer une facture, mettre à jour une commande). Une intégration par API est généralement plus robuste qu'une automatisation qui clique sur une interface.", relatedMethodSlug: "architecture-systeme-information" },
  { slug: "arr-mrr", term: "ARR / MRR", definition: "Le MRR (Monthly Recurring Revenue) est le revenu récurrent mensuel généré par les abonnements ; l'ARR (Annual Recurring Revenue) en est l'équivalent annuel. Ce sont les indicateurs de base d'un modèle économique par abonnement.", relatedMethodSlug: "modeles-affaires-numeriques" },
  { slug: "backlog", term: "Backlog", definition: "Liste priorisée des tâches, correctifs ou évolutions restant à traiter sur un produit ou un chantier. Un backlog non transféré à la fin d'une mission fait partie des éléments à documenter lors du transfert.", relatedMethodSlug: "mission-de-lexpert" },
  { slug: "benefit-owner", term: "Benefit owner", definition: "Personne responsable de la réalisation effective d'un bénéfice attendu (ex. le directeur commercial porte l'amélioration du taux de conversion, même si l'IT a livré le CRM). Chaque bénéfice majeur d'un business case doit avoir un owner identifié.", relatedMethodSlug: "roi-kpi-portefeuille-feuille-de-route" },
  { slug: "bpmn", term: "BPMN", definition: "Business Process Model and Notation : standard maintenu par l'Object Management Group qui fournit une notation commune pour représenter événements, activités, passerelles et flux d'un processus. Pour une petite mission, un diagramme en couloirs peut suffire.", relatedMethodSlug: "processus-bpmn-lean-refonte" },
  { slug: "business-case", term: "Business case", definition: "Document qui lie une situation actuelle à une amélioration mesurable, sur quatre familles de bénéfices : revenus supplémentaires, coûts évités, capacité libérée et réduction du risque. Présente toujours au moins deux options quand un choix architectural engage l'entreprise.", relatedMethodSlug: "fondements-et-maturite-numerique" },
  { slug: "cac", term: "CAC", definition: "Coût d'Acquisition Client = coûts d'acquisition / nouveaux clients attribués. Se compare toujours à la LTV (valeur vie client) pour juger de la rentabilité d'un canal d'acquisition.", relatedMethodSlug: "marketing-digital-et-mesure" },
  { slug: "chunking", term: "Chunking", definition: "Technique consistant à découper un contenu en blocs autonomes, chacun compréhensible sans avoir besoin de lire le reste de la page — utile pour l'extraction par les moteurs de réponse IA (AEO), mais une règle de lisibilité, pas un objectif mécanique en soi." },
  { slug: "consent-mode", term: "Consent Mode", definition: "Dispositif de Google qui permet d'ajuster le comportement des balises de mesure selon l'état de consentement de l'utilisateur (paramètres ad_storage, analytics_storage, ad_user_data, ad_personalization).", relatedMethodSlug: "marketing-digital-et-mesure" },
  { slug: "core-web-vitals", term: "Core Web Vitals", definition: "Ensemble d'indicateurs de performance web utilisés par Google pour juger la qualité d'expérience d'une page (temps de chargement, stabilité visuelle, réactivité)." },
  { slug: "data-lake", term: "Data lake", definition: "Stockage qui conserve des données à grande échelle dans des formats variés ; sans catalogue, ownership et règles de qualité, il peut devenir un stockage difficile à exploiter.", relatedMethodSlug: "strategie-data-bi-gouvernance" },
  { slug: "data-owner", term: "Data Owner", definition: "Rôle côté métier responsable d'une donnée : sa qualité, sa définition et son usage. À distinguer du Data Steward, qui est chargé de la qualité et des définitions au quotidien.", relatedMethodSlug: "strategie-data-bi-gouvernance" },
  { slug: "data-warehouse", term: "Data warehouse (entrepôt de données)", definition: "Système qui organise des données consolidées et structurées pour l'analyse et le pilotage, par opposition au data lake qui stocke des données brutes non transformées.", relatedMethodSlug: "strategie-data-bi-gouvernance" },
  { slug: "devops", term: "DevOps", definition: "Ensemble de pratiques (CI/CD, observabilité, séparation des environnements) visant à industrialiser le déploiement et l'exploitation des applications de façon fiable et reproductible.", relatedMethodSlug: "cloud-infrastructure-devops-couts" },
  { slug: "elt-etl", term: "ETL / ELT", definition: "ETL : Extract → Transform → Load. ELT : Extract → Load → Transform. Dans une architecture moderne, on charge souvent les données brutes dans une plateforme analytique avant de les transformer selon les besoins.", relatedMethodSlug: "strategie-data-bi-gouvernance" },
  { slug: "erp", term: "ERP", definition: "Système transactionnel central qui gère référentiels et transactions structurantes (clients, fournisseurs, stocks, facturation). Son intérêt dépend de la qualité des processus et des données qui l'alimentent — ce n'est pas une solution magique.", relatedMethodSlug: "operations-erp-supply-chain-iot" },
  { slug: "fanout-query", term: "Query fan-out", definition: "Méthode consistant à décomposer une requête principale en sous-requêtes probables qu'un moteur génératif peut lancer pour construire sa réponse (définitions, critères, alternatives, prix, preuves...), afin de couvrir ces angles dans un contenu." },
  { slug: "feuille-de-route", term: "Feuille de route (roadmap)", definition: "Système de décisions répondant à : où sommes-nous, quelle cible, quelles capacités manquent, quel ordre, quel budget, qui décide, comment mesurer. Une liste de logiciels avec des dates n'est pas une roadmap.", relatedMethodSlug: "roi-kpi-portefeuille-feuille-de-route" },
  { slug: "fine-tuning", term: "Fine-tuning", definition: "Technique consistant à adapter un modèle d'IA avec des exemples d'entraînement pour modifier certains de ses comportements, à distinguer du prompting (fournir des instructions au moment de l'usage).", relatedMethodSlug: "ia-rag-agents-mcp" },
  { slug: "freemium", term: "Freemium", definition: "Modèle qui donne un niveau gratuit pour acquérir et démontrer la valeur d'un produit, puis monétise certaines fonctions, un volume ou un service. Nécessite de contrôler le coût du service gratuit et le taux de conversion.", relatedMethodSlug: "modeles-affaires-numeriques" },
  { slug: "gmv", term: "GMV", definition: "Gross Merchandise Value : valeur totale des transactions passant par une marketplace, un indicateur clé pour évaluer son volume d'activité.", relatedMethodSlug: "modeles-affaires-numeriques" },
  { slug: "human-in-the-loop", term: "Human-in-the-loop", definition: "Principe consistant à définir les actions qui nécessitent une confirmation humaine avant exécution (paiement, remboursement, suppression de données, décision affectant fortement une personne). Un bouton \"Approuver\" sans contexte ne constitue pas un contrôle efficace.", relatedMethodSlug: "ia-rag-agents-mcp" },
  { slug: "iaas-paas-saas", term: "IaaS / PaaS / SaaS", definition: "Trois modèles cloud : IaaS fournit calcul, stockage et réseau (responsabilité client élevée) ; PaaS prend en charge une plus grande partie de la plateforme d'exécution ; SaaS livre l'application complète.", relatedMethodSlug: "cloud-infrastructure-devops-couts" },
  { slug: "idempotence", term: "Idempotence", definition: "Principe selon lequel une action répétée ne doit pas créer d'effet indésirable supplémentaire — un même événement reçu deux fois ne doit pas créer deux factures. Une règle de conception essentielle pour tout workflow automatisé.", relatedMethodSlug: "automatisation-api-rpa-low-code" },
  { slug: "iot", term: "IoT", definition: "Internet des objets : capteurs qui collectent des mesures (température, vibration, position, consommation). Un projet IoT doit commencer par l'information et l'action recherchées, pas par le choix d'un capteur.", relatedMethodSlug: "operations-erp-supply-chain-iot" },
  { slug: "kyc", term: "KYC", definition: "Know Your Customer : ensemble de vérifications réglementaires (identité, origine des fonds) imposées notamment dans le secteur bancaire et financier avant d'entrer en relation avec un client." },
  { slug: "llms-txt", term: "llms.txt", definition: "Fichier optionnel placé à la racine d'un site pour orienter les robots d'IA vers son contenu le plus pertinent. Il ne garantit ni indexation ni citation par un moteur IA — c'est une couche expérimentale, pas un facteur de classement Google." },
  { slug: "low-code-no-code", term: "Low-code / No-code", definition: "Plateformes (comme n8n ou Make) qui accélèrent la connexion de services et l'automatisation sans écrire tout le code manuellement. Un workflow codé reste préférable pour des volumes élevés ou une logique très spécifique.", relatedMethodSlug: "automatisation-api-rpa-low-code" },
  { slug: "ltv", term: "LTV", definition: "Lifetime Value (valeur vie client) : marge moyenne générée par un client sur toute la durée de la relation. LTV simplifiée ≈ marge moyenne par période × durée moyenne de relation — une formule à utiliser prudemment.", relatedMethodSlug: "modeles-affaires-numeriques" },
  { slug: "maturite-numerique", term: "Maturité numérique", definition: "Capacité réelle d'une organisation sur plusieurs dimensions (stratégie, processus, données, sécurité, automatisation...), évaluée sur une échelle de 0 (absent) à 5 (optimisé) — jamais réduite à un score global unique.", relatedMethodSlug: "fondements-et-maturite-numerique" },
  { slug: "mcp", term: "MCP (Model Context Protocol)", definition: "Spécification qui formalise des ressources, prompts et outils exposés par des serveurs pour standardiser l'interface entre applications IA et capacités externes. Une connexion à un outil donne un pouvoir d'action, d'où l'importance de l'authentification et des limites.", relatedMethodSlug: "ia-rag-agents-mcp" },
  { slug: "mer", term: "MER", definition: "Marketing Efficiency Ratio = revenu total / dépenses marketing. Complète le CAC et le ROAS pour juger l'efficacité globale d'une stratégie d'acquisition.", relatedMethodSlug: "marketing-digital-et-mesure" },
  { slug: "mfa", term: "MFA", definition: "Authentification multifacteur : mesure de sécurité prioritaire consistant à exiger plusieurs preuves d'identité pour accéder à un système, particulièrement pour les comptes administrateurs.", relatedMethodSlug: "cybersecurite-confidentialite-resilience" },
  { slug: "nist-ai-rmf", term: "NIST AI RMF", definition: "Cadre de gestion du risque IA organisé autour de quatre fonctions : Govern, Map, Measure et Manage. Sert de référence pour structurer la gouvernance IA d'une entreprise.", relatedMethodSlug: "ia-rag-agents-mcp" },
  { slug: "nist-csf", term: "NIST CSF 2.0", definition: "Cybersecurity Framework qui organise les résultats de cybersécurité autour de six fonctions : Govern, Identify, Protect, Detect, Respond et Recover.", relatedMethodSlug: "cybersecurite-confidentialite-resilience" },
  { slug: "nrr", term: "Net Revenue Retention (NRR)", definition: "= (revenu début − churn − contraction + expansion) / revenu début. Mesure si les clients existants génèrent plus ou moins de revenu dans le temps, indépendamment de l'acquisition de nouveaux clients.", relatedMethodSlug: "modeles-affaires-numeriques" },
  { slug: "nps-csat-ces", term: "NPS / CSAT / CES", definition: "Trois indicateurs d'expérience client : NPS (Net Promoter Score) mesure la recommandation, CSAT la satisfaction, CES l'effort perçu. Le NPS seul ne remplace pas les mesures comportementales.", relatedMethodSlug: "ux-produit-experience-client" },
  { slug: "otif-oee", term: "OTIF / OEE", definition: "OTIF (On Time In Full) mesure la fiabilité des livraisons ; OEE (Overall Equipment Effectiveness) mesure la performance globale d'un équipement de production. Deux KPI opérationnels selon le contexte industriel ou logistique.", relatedMethodSlug: "operations-erp-supply-chain-iot" },
  { slug: "owasp", term: "OWASP", definition: "Organisation qui publie des référentiels de sécurité (Top 10 des risques applicatifs web, référentiel pour applications LLM/GenAI) servant de point de départ à la sensibilisation à la sécurité applicative.", relatedMethodSlug: "cybersecurite-confidentialite-resilience" },
  { slug: "payback", term: "Payback", definition: "= investissement initial / gain mensuel net. Indique le nombre de mois nécessaires pour qu'un investissement se rembourse par les gains qu'il génère.", relatedMethodSlug: "fondements-et-maturite-numerique" },
  { slug: "persona", term: "Persona", definition: "Description d'une situation de décision réelle (contexte, tâche, critères, objections), fondée sur des entretiens et des données — pas un personnage décoratif avec des détails démographiques inventés.", relatedMethodSlug: "ux-produit-experience-client" },
  { slug: "prompting", term: "Prompting", definition: "Action de fournir des instructions, du contexte et des exemples à un modèle d'IA générative pour orienter sa réponse, sans modifier le modèle lui-même (à la différence du fine-tuning).", relatedMethodSlug: "ia-rag-agents-mcp" },
  { slug: "raci", term: "RACI", definition: "Matrice de responsabilités : Responsible, Accountable, Consulted, Informed. Sert à clarifier qui fait quoi sur une décision, sans produire une matrice géante que personne ne consulte.", relatedMethodSlug: "conduite-du-changement-gouvernance-delivery" },
  { slug: "rag", term: "RAG", definition: "Retrieval-Augmented Generation : technique consistant à rechercher des éléments dans une source externe et à les injecter dans le contexte d'un modèle d'IA. Ce n'est pas une base de données de remplacement — la qualité documentaire et les droits d'accès restent nécessaires.", relatedMethodSlug: "ia-rag-agents-mcp" },
  { slug: "roas", term: "ROAS", definition: "Return On Ad Spend = revenu attribué / dépenses publicitaires. Un ROAS élevé ne garantit pas une campagne rentable si le coût d'acquisition dépasse la marge réelle.", relatedMethodSlug: "marketing-digital-et-mesure" },
  { slug: "roi", term: "ROI", definition: "Retour sur investissement simple = (gain annuel net − investissement initial) / investissement initial. Un des quatre indicateurs de base de tout business case, avec le TCO, le payback et le gain annuel brut.", relatedMethodSlug: "fondements-et-maturite-numerique" },
  { slug: "rpo-rto", term: "RPO / RTO", definition: "RPO (quantité maximale de données que l'on accepte de perdre) et RTO (durée maximale de restauration) définissent le niveau d'exigence d'une stratégie de sauvegarde, à adapter selon la criticité du système.", relatedMethodSlug: "cloud-infrastructure-devops-couts" },
  { slug: "shadow-it", term: "Shadow IT", definition: "Outils utilisés dans une entreprise sans gouvernance formelle : comptes personnels, SaaS gratuits, feuilles de calcul contenant des données sensibles. Un point d'attention systématique lors d'un audit de sécurité.", relatedMethodSlug: "cybersecurite-confidentialite-resilience" },
  { slug: "sla", term: "SLA", definition: "Service Level Agreement : engagement de délai ou de qualité de service, par exemple un délai de premier contact garanti sur une demande entrante ou de résolution d'un ticket support.", relatedMethodSlug: "crm-vente-service-client-omnicanal" },
  { slug: "source-de-verite", term: "Source de vérité", definition: "Système désigné comme faisant autorité sur une donnée précise (ex. le CRM pour le statut d'une opportunité, l'ERP pour la facture). Évite la synchronisation bidirectionnelle par défaut, qui crée des conflits.", relatedMethodSlug: "architecture-systeme-information" },
  { slug: "tco", term: "TCO", definition: "Coût total de possession : inclut licences, développement, intégration, infrastructure, migration, support, formation, sécurité et maintenance — pas seulement le coût de licence initial.", relatedMethodSlug: "fondements-et-maturite-numerique" },
  { slug: "wcag", term: "WCAG", definition: "Web Content Accessibility Guidelines : recommandation de référence pour l'accessibilité du contenu web (navigation clavier, contrastes, structure sémantique, textes alternatifs).", relatedMethodSlug: "ux-produit-experience-client" },
];

export function getGlossaryTerm(slug: string): GlossaryTerm | undefined {
  return GLOSSARY_TERMS.find((t) => t.slug === slug);
}
